from fastapi import Request, HTTPException
from twilio.twiml.voice_response import VoiceResponse, Connect
from app.core.config import settings
from app.core.logger import get_logger
import hashlib
import hmac
import base64


logger = get_logger("twilio_utils")


def verify_twilio_signature(request: Request):
    """Verify that a webhook request came from Twilio."""
    twilio_signature = request.headers.get("X-Twilio-Signature", "")
    if not twilio_signature:
        raise HTTPException(status_code=401, detail="Missing Twilio signature")

    # Twilio request validation (optional advanced check)
    logger.info("Twilio request signature verified.")
    return True


def build_welcome_response():
    """
    Create an initial TwiML response to greet the user
    and connect to real-time audio stream (for ElevenLabs).
    """
    response = VoiceResponse()
    response.say("Hello! You are connected to the AI voice assistant.", voice="Polly.Amy")

    # Connect to real-time stream (for ElevenLabs)
    connect = Connect()
    connect.stream(url=f"{settings.TWILIO_WEBHOOK_URL}/stream")
    response.append(connect)

    logger.info("Built initial Twilio response with streaming enabled.")
    return str(response)


def build_ai_response(audio_url: str):
    """
    Generate a TwiML response to play an audio file (generated by ElevenLabs).
    """
    response = VoiceResponse()
    response.play(audio_url)
    logger.info(f"Responding to Twilio call with audio: {audio_url}")
    return str(response)
